In [ ]:
조건 : 아나콘다가 환경패스로 지정 
0) 쥬피터노트북의 시작 작업폴더 생성및 경로 확인 
EX - C:\workspace211123
1) 쥬피터노트북 실행 파일 찾기 
C:\ProgramData\Anaconda3\Scripts 폴더안에 
    jupyter-notebook.exe
2)  jupyter-notebook.exe 마우스 우측 버튼 클릭 후 
[보내기]-[바탕화면에 바로가기 만들기]
3) 바탕화면에 아이콘 확인 하고 
마우스 우측버튼 클릭후 [속성] 탭 클릭 
[시작위치]를 위에서 생성한 작업폴더경로로 설정한다. 
C:\workspace211123
    

In [4]:
ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 2819-FF50

 C:\workspace211123 디렉터리

2021-11-23  오전 10:10    <DIR>          .
2021-11-23  오전 10:10    <DIR>          ..
2021-11-23  오전 09:31    <DIR>          .ipynb_checkpoints
2021-11-23  오전 09:29    <DIR>          data
2021-11-23  오전 10:10             2,885 day101_np.ipynb
2021-11-23  오전 09:27    <DIR>          step1_Numpy
2021-11-20  오전 11:12    <DIR>          step2_Pandas
2021-11-20  오전 11:13    <DIR>          step3_Visual
2021-11-20  오후 10:13    <DIR>          step4_ML
2021-11-20  오후 01:26    <DIR>          산출물샘플
2021-11-23  오전 08:36    <DIR>          참조
               1개 파일               2,885 바이트
              10개 디렉터리  73,061,191,680 바이트 남음


In [5]:
ls data

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 2819-FF50

 C:\workspace211123\data 디렉터리

2021-11-23  오전 09:29    <DIR>          .
2021-11-23  오전 09:29    <DIR>          ..
2021-11-23  오전 12:12             3,088 births.txt
2021-11-23  오전 12:25            35,455 Jeju2021.csv
2016-07-17  오후 09:46           171,308 movies.dat
2018-04-24  오전 10:42        24,594,131 ratings.dat
2019-03-20  오전 10:54         1,185,149 seoul.csv
2021-01-31  오후 08:49            93,805 seoul2021.csv
               6개 파일          26,082,936 바이트
               2개 디렉터리  73,060,519,936 바이트 남음


In [6]:
import os 

# 현재 작업폴더 위치 확인 
os.getcwd()

'C:\\workspace211123'

In [9]:
# 쥬피터노트북 셀 스타일 조절 
from IPython.core.display import display, HTML
display(HTML("<style>.container { font-weight: bold !important; }</style>"))
display(HTML("<style>.container { width: 100% !important; }</style>"))

# 경고 메세지 숨기기 
import warnings
warnings.filterwarnings(action='ignore')

# Numpy 개요

- Numeric + Python = Numpy
- 수학 및 과학 연산을 위한 파이썬 패키지
- 배열이나 행렬 계산에 용이한 메서드를 제공
- 한글로 넘파이로 주로 통칭, 넘피/늄파이라고 부르기도 함
- 관련 사이트 : http://www.numpy.or

# Numpy 임포트 및 정보 확인 

In [10]:
import numpy as np

In [11]:
#  버전 확인 
np.__version__

'1.20.1'

In [14]:
# 메소드와 속성 확인 
# print(dir(np))

In [15]:
# 넘파이 각 속성과 메서드 레퍼런스 확인은?
# 넘파이명령어?
np.mean?

# 넘파이 배열 생성 

- 리스트 => 넘파이 배열 
```
np.array(리스트)
```
- 관련 속성 
```
ndim : 차원 반환 => int
size : 전체 길이 반환  => int
shape : 구조 반환 => tuple 
```

In [17]:
# 1차원 리스트 => 1차원 넘파이 배열 
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList) )

[10, 56, 77, 23, 44] <class 'list'> 5


In [19]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr) )
print(f'차원은? {myArr.ndim}')
print(f'구조는? {myArr.shape}, {type(myArr.shape)}')
print(f'길이는? {myArr.size}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원은? 1
구조는? (5,), <class 'tuple'>
길이는? 5


In [20]:
# print() 문을 사용하지 않고 넘파이 배열 출력
myArr

array([10, 56, 77, 23, 44])

In [21]:
# 2차원 리스트 => 넘파이 배열 
myList2 = [[1, 2, 3], [10, 20, 30], [100, 200, 300]]
myList2

[[1, 2, 3], [10, 20, 30], [100, 200, 300]]

In [24]:
myArr2 = np.array(myList2)
# len() 결과값이 2차원인 경우에는 행수로 출력 
print(myArr2, type(myArr2), len(myArr2) )
print(f'차원은? {myArr2.ndim}')
print(f'구조는? {myArr2.shape}, {type(myArr2.shape)}')
print(f'길이는? {myArr2.size}')
print(f'넘파이 배열은 {myArr2.shape[0]} 행 {myArr2.shape[1]} 열')

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원은? 2
구조는? (3, 3), <class 'tuple'>
길이는? 9
넘파이 배열은 3 행 3 열


In [25]:
myArr2

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [26]:
# 2차원 리스트에서 각 행 수가 틀린 경우 테스트 
# 넘파이 배열은?
myList3 = [[1, 2], [10, 20, 30], [100, 200, 300, 400, 500]]
myList3, len(myList3)

([[1, 2], [10, 20, 30], [100, 200, 300, 400, 500]], 3)

In [27]:
# 각행의 갯수가 틀린 경우  넘파이배열로 생성하면 
# list([값...]) 형태로 삽입된다. 
myArr3 = np.array(myList3)
myArr3

array([list([1, 2]), list([10, 20, 30]), list([100, 200, 300, 400, 500])],
      dtype=object)

# 넘파이 배열과 리스트와의 차이점은?

- 연산이 가능 => 브로드캐스팅 
- 배열간의 연산도 가능 
- 리스트는 자료형 혼합 가능. 넘파이 배열은 하나의 자료형만 가능 
- 넘파이에서 지원되는 메서드 사용 가능 : 평균, 상관계수, 분산, 표준편차, 최빈값

In [28]:
# 리스트의 경우 + - 리스트간의 연결 
listA = [10, 40, 50]
listB = [10, 40, 50]
listA + listB

[10, 40, 50, 10, 40, 50]

In [30]:
# 리스트의 경우 * - 리스트의 반복 
# listA * listB => Type error
listA * 2

[10, 40, 50, 10, 40, 50]

In [31]:
# 넘파이 배열간의 연산 
# 각 위치에 해당하는 요소간의 연산으로 반환 
arrA = np.array([10, 40, 50])
arrB = np.array([5, 4, 3])
print(arrA + arrB)
print(arrA - arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB)
print(arrA % arrB)

[15 44 53]
[ 5 36 47]
[ 50 160 150]
[ 2.         10.         16.66666667]
[ 2 10 16]
[0 0 2]


In [34]:
# 브로드캐스팅 
# 넘파이배열 연산자 숫자 
# 넘파이배열 각각에 연산이 적용된다. 
arrA
print(arrA)
print(arrA * 2)
print(arrA // 3)

[10 40 50]
[ 20  80 100]
[ 3 13 16]


In [36]:
# 리스트와 넘파이배열의 자료형 테스트 
myList_c = ['홍길동', 100, 3.14, True, False]
myList_c, type(myList_c)

(['홍길동', 100, 3.14, True, False], list)

In [37]:
# 넘파이 배열의 구성 요소의 자료형 확인은?
# 넘파이배열명.dtype

# 데이타가 혼합되어 있는 경우 자동형변환이 된다. 
# 문자열 넘파이 배열로 변경 
myArr_c = np.array(['홍길동', 100, 3.14, True, False])
myArr_c, type(myArr_c), myArr_c.dtype

(array(['홍길동', '100', '3.14', 'True', 'False'], dtype='<U32'),
 numpy.ndarray,
 dtype('<U32'))

In [38]:
# 정수랑 실수 혼합된 넘파이 배열 생성 
myArr_d = np.array([100, 3.14, 23.5, 0])
myArr_d, type(myArr_d), myArr_d.dtype

(array([100.  ,   3.14,  23.5 ,   0.  ]), numpy.ndarray, dtype('float64'))

In [39]:
# 통계함수 적용하기 
# np.통계함수명(넘파이배열명, 옵션)
# 넘파이배열명.통계함수명(옵션)
myArr_d

array([100.  ,   3.14,  23.5 ,   0.  ])

In [46]:
print(f' 배열의 모든합은? {np.sum(myArr_d)}  {myArr_d.sum()}')
print(f' 배열의 평균은? {np.mean(myArr_d)}  {myArr_d.mean()}')
print(f' 배열의 최댓값은? {np.max(myArr_d)}  {myArr_d.max()}')
print(f' 배열의 최솟값은? {np.min(myArr_d)}  {myArr_d.min()}')

 배열의 모든합은? 126.64  126.64
 배열의 평균은? 31.66  31.66
 배열의 최댓값은? 100.0  100.0
 배열의 최솟값은? 0.0  0.0


In [47]:
print(f' 배열의 중앙값은? {np.median(myArr_d)}  {myArr_d.median()}')

AttributeError: 'numpy.ndarray' object has no attribute 'median'