In [1]:
import numpy as np

# Quiz 15

```
birthArr = np.loadtxt('data/births.txt',delimiter=',', dtype=np.int64)

1. 남아 ,여아 출생 평균을 구하여라
2. 남아출생이 가장많은 top5  를 구하여라(년도와 남아수)
3. 남아율(%) 을 구하고 각년도별  남아수가 차지하는비율을 데이터로  출력하여라 

년도    남아    여아    남아율
=================================
..
4. 2000년도 이후데이터 에 대해  출생량 을 구하고 
남아수가 1800000 이상이면 '많음'아니면 '적음' 이라고 출력하여라


	남아수 출생량
2000   1814601   '많음'
2001   1799049   '적음'


5.1800년대,1900년대,2000년대 각 남아,여야수 평균을 구하여라

```

In [6]:
ls

211117_tf.Variable.ipynb     DM_Assignment_2.ipynb  ratings.dat
211123_visualize_day1.ipynb  Jeju2021.csv           seoul2021.csv
births.txt                   movies.dat             seoul.csv
data.zip                     Numpy_Quiz.ipynb
DM_Assignment_1.ipynb        Q15_jhj_answer.ipynb


In [5]:
import os
os.chdir('drive/MyDrive/2021_하반기교육')

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
birthArr = np.loadtxt('births.txt',delimiter=',', dtype=np.int64)

In [14]:
birthArr

array([[   1880,   90993,  110491],
       [   1881,   91954,  100745],
       [   1882,  107850,  113688],
       [   1883,  112321,  104629],
       [   1884,  129022,  114445],
       [   1885,  133055,  107800],
       [   1886,  144535,  110784],
       [   1887,  145982,  101414],
       [   1888,  178627,  120853],
       [   1889,  178366,  110584],
       [   1890,  190377,  111025],
       [   1891,  185482,  101196],
       [   1892,  212346,  122037],
       [   1893,  212906,  112317],
       [   1894,  222922,  115772],
       [   1895,  233630,  117398],
       [   1896,  237920,  119570],
       [   1897,  234202,  112758],
       [   1898,  258770,  122693],
       [   1899,  233023,  106212],
       [   1900,  299828,  150499],
       [   1901,  239348,  106471],
       [   1902,  264077,  122659],
       [   1903,  261973,  119234],
       [   1904,  275371,  128125],
       [   1905,  291629,  132319],
       [   1906,  295303,  133159],
       [   1907,  318566,  1

1. 남아 ,여아 출생 평균을 구하여라

In [13]:
boy = birthArr[:,1]
print(boy)
boy_mean = boy.mean()
girl = birthArr[:,2]
print(girl)
girl_mean = girl.mean()

[  90993   91954  107850  112321  129022  133055  144535  145982  178627
  178366  190377  185482  212346  212906  222922  233630  237920  234202
  258770  233023  299828  239348  264077  261973  275371  291629  295303
  318566  334313  347228  396501  418299  558103  624518  761548  983874
 1044323 1081280 1157647 1130145 1198283 1232999 1200919 1206330 1248876
 1217352 1185304 1192330 1153117 1116422 1125761 1064497 1066994 1007710
 1044039 1048428 1040202 1063872 1103277 1096518 1143325 1207919 1350545
 1395082 1327104 1307028 1571184 1772644 1697814 1710825 1713180 1800042
 1854698 1880326 1941682 1954664 2007512 2044160 2010884 2023044 2022093
 2017316 1966548 1927217 1894594 1765001 1691868 1650764 1640103 1686947
 1748147 1663475 1521185 1458139 1467413 1457699 1465096 1532997 1531658
 1605051 1659933 1667465 1692678 1670061 1682973 1720036 1714664 1737891
 1779839 1843105 1897709 1874434 1843304 1808379 1785074 1757927 1752249
 1739806 1765915 1772632 1814601 1799049 1795206 18

In [12]:
print('boy_mean:',boy_mean)
print('girl_mean:',girl_mean)

boy_mean: 1225776.0681818181
girl_mean: 1245399.2121212122


2. 남아출생이 가장많은 top5  를 구하여라(년도와 남아수)

In [20]:
#idx = np.argsort(boy)[-5:][::-1]
#print(idx)

#print(boy[np.argsort(boy)[-5:][::-1]])

print('year and boy birth:',birthArr[np.argsort(boy)[-5:][::-1],0:2])

year and boy birth: [[   1957 2044160]
 [   1959 2023044]
 [   1960 2022093]
 [   1961 2017316]
 [   1958 2010884]]


```
3. 남아율(%) 을 구하고 각년도별  남아수가 차지하는비율을 데이터로  출력하여라 

년도    남아    여아    남아율
=================================
..
```

In [21]:
boy_rate = (boy/(boy + girl) * 100).reshape(132,1)

In [22]:
birthArr.shape

(132, 3)

In [23]:
boy_rate.shape

(132, 1)

In [24]:
boy_rate = boy_rate.astype(dtype='int64')

In [25]:
boy_rate_added = np.append(birthArr, boy_rate, axis=1)

In [26]:
print(boy_rate_added)

[[   1880   90993  110491      45]
 [   1881   91954  100745      47]
 [   1882  107850  113688      48]
 [   1883  112321  104629      51]
 [   1884  129022  114445      52]
 [   1885  133055  107800      55]
 [   1886  144535  110784      56]
 [   1887  145982  101414      59]
 [   1888  178627  120853      59]
 [   1889  178366  110584      61]
 [   1890  190377  111025      63]
 [   1891  185482  101196      64]
 [   1892  212346  122037      63]
 [   1893  212906  112317      65]
 [   1894  222922  115772      65]
 [   1895  233630  117398      66]
 [   1896  237920  119570      66]
 [   1897  234202  112758      67]
 [   1898  258770  122693      67]
 [   1899  233023  106212      68]
 [   1900  299828  150499      66]
 [   1901  239348  106471      69]
 [   1902  264077  122659      68]
 [   1903  261973  119234      68]
 [   1904  275371  128125      68]
 [   1905  291629  132319      68]
 [   1906  295303  133159      68]
 [   1907  318566  146833      68]
 [   1908  334313  1

```
4. 2000년도 이후데이터 에 대해  출생량 을 구하고 
남아수가 1800000 이상이면 '많음'아니면 '적음' 이라고 출력하여라


	남아수 출생량
2000   1814601   '많음'
2001   1799049   '적음'
```

In [28]:
after_2000 = birthArr[birthArr[:,0] > 2000]
print(after_2000)

[[   2001 1799049 1941251]
 [   2002 1795206 1939815]
 [   2003 1825359 1973434]
 [   2004 1834145 1982794]
 [   2005 1845379 1994841]
 [   2006 1898463 2052377]
 [   2007 1919408 2072139]
 [   2008 1887234 2036289]
 [   2009 1832925 1979303]
 [   2010 1772738 1913851]
 [   2011 1753500 1893230]]


In [29]:
result = np.where(after_2000[:,1]>=1800000,'많음','적음')

In [30]:
result = result.reshape(11,1)

In [31]:
str_aft_2000 = after_2000.astype(dtype='<U10')

In [32]:
str_aft_2000_added = np.append(str_aft_2000, result, axis=1)

In [33]:
print(str_aft_2000_added)

[['2001' '1799049' '1941251' '적음']
 ['2002' '1795206' '1939815' '적음']
 ['2003' '1825359' '1973434' '많음']
 ['2004' '1834145' '1982794' '많음']
 ['2005' '1845379' '1994841' '많음']
 ['2006' '1898463' '2052377' '많음']
 ['2007' '1919408' '2072139' '많음']
 ['2008' '1887234' '2036289' '많음']
 ['2009' '1832925' '1979303' '많음']
 ['2010' '1772738' '1913851' '적음']
 ['2011' '1753500' '1893230' '적음']]


```
5.1800년대,1900년대,2000년대 각 남아,여야수 평균을 구하여라
```

In [41]:
b_a_1800 = birthArr[(birthArr[:,0] >= 1800) & (birthArr[:,0] < 1900)]
b_a_1900 = birthArr[(birthArr[:,0] >= 1900) & (birthArr[:,0] < 2000)]
b_a_2000 = birthArr[(birthArr[:,0] >= 2000) & (birthArr[:,0] < 2100)]

In [48]:
boy_1800 = b_a_1800[:,1]
boy_mean_1800 = boy_1800.mean()
girl_1800 = b_a_1800[:,2]
girl_mean_1800 = girl_1800.mean()

In [49]:
print(boy_mean_1800)
print(girl_mean_1800)

176714.15
111820.55


In [50]:
boy_1900 = b_a_1900[:,1]
boy_mean_1900 = boy_1900.mean()
girl_1900 = b_a_1900[:,2]
girl_mean_1900 = girl_1900.mean()

In [51]:
print(boy_mean_1900)
print(girl_mean_1900)

1362901.51
1384145.55


In [52]:
boy_2000 = b_a_2000[:,1]
boy_mean_2000 = boy_2000.mean()
girl_2000 = b_a_2000[:,2]
girl_mean_2000 = girl_2000.mean()

In [53]:
print(boy_mean_2000)
print(girl_mean_2000)

1831500.5833333333
1978477.5
