In [104]:
# 쥬피터노트북 셀 스타일 조절 
from IPython.core.display import display, HTML
display(HTML("<style>.container { font-weight: bold !important; }</style>"))
display(HTML("<style>.container { width: 100% !important; }</style>"))

# 경고 메세지 숨기기 
import warnings
warnings.filterwarnings(action='ignore')

In [103]:
import numpy as np

# 넘파이 제공 함수를 이용해서 배열 생성하기 

```
np.ones(n) , np.ones((x, y)) 
np.zeros(n) , np.zeros((x, y))
np.empty(n) , np.empty((x, y))
np.arange(start, end, step) 

# 1차원 => 2차원
reshape(x, y)
# 2차원 => 1차원
flatten()
```

In [5]:
# 1. 로 구성된 넘파이 배열 생성 => 실수형
arr1 = np.ones(10)
arr1, arr1.dtype

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), dtype('float64'))

In [6]:
# 1 로 구성된 넘파이 배열 생성 => 정수형 
arr2 = np.ones(10, dtype=int)
arr2, arr2.dtype

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), dtype('int32'))

In [7]:
# 1 로 구성된 5행 2열 배열 생성 => 정수형 
arr3 = np.ones((5,2), dtype=int)
arr3, arr3.dtype, arr3.shape

(array([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]),
 dtype('int32'),
 (5, 2))

In [10]:
# 3행 3열 0으로 구성된 넘파이 배열 
print( np.array([[0,0,0], [0,0,0], [0,0,0]]) )
arr4 = np.zeros((3,3), dtype=int)
print('='*30)
print(arr4)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [11]:
# 5행 5열로 구성된 넘파이 배열 
arr5 = np.empty((5,5))
arr5

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307, 1.89146896e-307],
       [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.15710088e-306, 6.23056330e-307,
        1.60219578e-306, 7.56601165e-307],
       [6.23061763e-307, 9.34607074e-307, 8.90098127e-307,
        8.90108313e-307, 6.23053954e-307],
       [1.24611741e-306, 1.37961506e-306, 1.42410974e-306,
        3.39986383e-317, 3.39986383e-317]])

In [16]:
# 1~20 으로 구성된 4행 5열의 넘파이 배열 

# range() 객체 => 리스트화 list(range()) => 넘파이 배열화 np.array(list(range()))
print(range(1,21), list(range(1,21)))
print(np.array(list(range(1,21))))
print('='*30)
# reshape(x, y) => x행 y열 로 재구성 
arr6 = np.arange(1, 21).reshape(4, 5)
arr6

range(1, 21) [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [23]:
# 0~49 까지 구성된 넘파이 배열
# 초기값이 0인 경우 생략 가능 
arr7 = np.arange(50)
print(arr7, len(arr7), arr7.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [24]:
print(arr7.reshape(10,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [26]:
# 원본 넘파이 배열에 다시 적용 
arr7 = arr7.reshape(10,5)
arr7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [28]:
# 2차원 => 2차원 변경 가능 
arr8 = arr7.reshape(5,10)
arr8

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [29]:
# 2차원 => 1차원으로 변경 
# 넘파이배열.flatten()
arr8.ndim, arr8.shape

(2, (5, 10))

In [34]:
arr9 = arr8.flatten()
arr9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [33]:
arr8

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [36]:
# 0~100 사이의 숫자중에서 짝수로된 넘파이 배열 생성
arr10 = np.arange(0, 101, 2)
arr10

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [39]:
# 홀수는?
np.arange(1, 101, 2).reshape(25,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23],
       [25, 27],
       [29, 31],
       [33, 35],
       [37, 39],
       [41, 43],
       [45, 47],
       [49, 51],
       [53, 55],
       [57, 59],
       [61, 63],
       [65, 67],
       [69, 71],
       [73, 75],
       [77, 79],
       [81, 83],
       [85, 87],
       [89, 91],
       [93, 95],
       [97, 99]])

In [40]:
arr11 = np.arange(1,31)
arr11, arr11.ndim

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 1)

In [42]:
# reshape(-1, n) => 2차원 n개의 컬럼으로 구성 
arr12 = arr11.reshape(-1, 1)
# arr12, arr12.ndim

In [44]:
np.arange(1,21).reshape(-1, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [45]:
# np.arange(1,21).reshape(10, 2)
np.arange(1,21).reshape(-1, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

# 넘파이배열의 자료형 형변환 
```
배열명2 = 배열명1.astype(자료형)
자료형 = np.float64, np.int32
```

In [50]:
# 정수형, 3행 3열
matrix = np.arange(1,10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [51]:
# 실수형, 3행 3열
matrix = np.arange(1,10, dtype=float).reshape(3,3)
matrix, matrix.dtype

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 dtype('float64'))

In [56]:
# 문자열형, 3행 3열
matrix = np.arange(1,10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [58]:
# 정수형 => 문자열형 
matrix.astype('<U5')

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U5')

In [60]:
# 논리형으로 구성된 넘파이 배열 생성 
matrix2 = np.array([True, False, True, True, False])
matrix2, matrix2.dtype

(array([ True, False,  True,  True, False]), dtype('bool'))

In [62]:
# 논리형 => 정수형 
# True => 1, False => 0
matrix2.astype(int), matrix2.astype(int).dtype

(array([1, 0, 1, 1, 0]), dtype('int32'))

In [63]:
# 논리형 => 문자열 
matrix2.astype('<U5')

array(['True', 'False', 'True', 'True', 'False'], dtype='<U5')

In [65]:
# 문자열숫자 => 정수나 실수 
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3

array(['3.14', '5.5', '0.78'], dtype='<U4')

In [67]:
matrix3.astype(float), matrix3.astype(float).dtype

(array([3.14, 5.5 , 0.78]), dtype('float64'))

In [69]:
# ValueError
# matrix3.astype(int)

In [73]:
matrix4 = np.array(['3', '5', '0'])
matrix4.astype(int)

array([3, 5, 0])

In [71]:
# ValueError
# matrix3.astype(bool)

# 넘파이배열의 인덱싱

```
넘파이배열명[Index]
넘파이배열명[i, j] = 넘파이배열명[i][j] => i 행 j 열 

```

In [74]:
matrix_a = np.arange(10)
matrix_b = np.arange(12).reshape(3,4)

In [75]:
matrix_a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
matrix_b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
# 1차원에서 첫요소와 마지막 요소 
matrix_a[0], matrix_a[-1]

(0, 9)

In [80]:
# 2차원에서 1행 1열 
matrix_b[0, 0], matrix_b[0][0]

(0, 0)

In [82]:
# 2차원에서 마지막행 마지막열 => 3행4열
matrix_b[-1, -1], matrix_b[-1][-1], matrix_b[2][3]

(11, 11, 11)

In [86]:
# matrix_b 에서 3행1열의 값을 100으로 교체하여라 
matrix_b[2, 0] = 100

In [87]:
matrix_b

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [100,   9,  10,  11]])

In [97]:
# 리스트경우의 인덱싱 
a = [[1, 2, 3], [1, 2, 3]]
a[0][0]
# 에러 발생 TypeError
# a[0,0] 

1

# 넘파이배열의 슬라이싱 : 1차원

```
넘파이배열명[start:end:step]
넘파이배열명[start:end]
넘파이배열명[start:]
넘파이배열명[:end]

- 역순으로 표시 
넘파이배열명[::-1] 

```

In [89]:
matrix_c = np.arange(0, 101, 10)
matrix_c 

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [98]:
matrix_c[1:7:2]

array([10, 30, 50])

In [99]:
matrix_c[:7]

array([ 0, 10, 20, 30, 40, 50, 60])

In [100]:
matrix_c[5:]

array([ 50,  60,  70,  80,  90, 100])

In [101]:
matrix_c[::2]

array([  0,  20,  40,  60,  80, 100])

In [106]:
# 역순 배열명[::-1]
print(matrix_c)
print(matrix_c[::-1])

[  0  10  20  30  40  50  60  70  80  90 100]
[100  90  80  70  60  50  40  30  20  10   0]


# 넘파이배열의 슬라이싱 : 2차원

```
넘파이배열명[start1:end1:step1, start2:end2:step2]

- 역순으로 표시 
넘파이배열명[::-1, ::] 
넘파이배열명[::, ::-1] 
```

In [108]:
# 5행 5열 
matrix_d =np.arange(1,26).reshape(5,5)
matrix_d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [109]:
# 1행만 출력 
matrix_d[0, ::]

array([1, 2, 3, 4, 5])

In [111]:
# 1,2행만 출력 
matrix_d[0:2, ::]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [113]:
# 1열만 출력 
matrix_d[::, 0]

array([ 1,  6, 11, 16, 21])

In [114]:
# 3,4열만 출력 
matrix_d[::, 2:4:]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])

In [118]:
# 특정행의 특정열 슬라이싱 
matrix_d[0:3:, 0:2:]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [119]:
# 홀수번째 행만 출력 
matrix_d[::2, ::]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [120]:
# 홀수번째 열만 출력 
matrix_d[::, ::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20],
       [21, 23, 25]])

In [121]:
# 짝수번째행 + 짝수번째 열만 출력 
matrix_d[1::2, 1::2]

array([[ 7,  9],
       [17, 19]])

In [122]:
# 행우선 역순 
matrix_d[::-1, ::]

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [123]:
# 컬럼우선으로 역순 
matrix_d[::, ::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16],
       [25, 24, 23, 22, 21]])

In [115]:
matrix_d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# 전치 행렬 
- 행과 열의 구조를 변경 
넘파이배열.T

In [125]:
# 3행 2열 
matrix_e =np.arange(1,7).reshape(3,2)
matrix_e

array([[1, 2],
       [3, 4],
       [5, 6]])

In [127]:
# 2행 3열 
matrix_e.T

array([[1, 3, 5],
       [2, 4, 6]])

In [128]:
matrix_e.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

# 난수로 구성된 넘파이 배열 생성 

```
 np.random.randint(start, end, n ) 정수로된 난수 생성  
 np.random.randint(start, end, (i, j) ) i*j 구조로된 난수 2차원 넘파이 배열 생성 
```

In [131]:
np.random?

In [135]:
# 1~10 사이의 숫자중에서 10개 출력  
np.random.randint(1, 10, 10) 

array([2, 5, 6, 1, 8, 9, 2, 3, 6, 8])

In [134]:
# 1~10 사이의 숫자중에서 임의로 뽑아서 2차원 배열 생성  
np.random.randint(1, 10, (5,2)) 

array([[5, 1],
       [3, 9],
       [8, 7],
       [5, 9],
       [1, 9]])

#### 섞기 
```
np.random.shuffle(넘파이배열)
원본 배열에 바로 적용
```

In [136]:
np.random.shuffle?

In [137]:
matrix_e = np.arange(1,11)
matrix_e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [138]:
np.random.shuffle(matrix_e)

In [139]:
matrix_e

array([ 7,  9,  4,  3, 10,  5,  8,  2,  6,  1])

In [140]:
# np.random.shuffle(matrix_e) print 문과 사용시 None 출력 
print(np.random.shuffle(matrix_e))

None


In [141]:
print(matrix_e)

[ 6  2  9  5  4  7  1  3  8 10]


In [142]:
matrix = np.arange(1,47)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46])

In [143]:
np.random.shuffle(matrix)
matrix

array([21,  7, 42, 26, 22, 34, 15, 44,  6, 40, 31, 13,  3, 20, 24, 33,  8,
        2, 46, 39, 19,  1,  9, 43, 35, 10, 37, 36, 32, 38, 23, 27,  4, 14,
       28, 12, 45, 29, 11,  5, 41, 17, 16, 30, 18, 25])

In [144]:
lotto_num = matrix[:6]
lotto_num

array([21,  7, 42, 26, 22, 34])

#### 실수 난수 
```
np.random.randn(n)
np.random.randn(i,j)
```

In [148]:
matrix1 = np.random.randn(10)
matrix2 = np.random.randn(4,4)

In [149]:
matrix1

array([ 1.08762795,  1.28832662, -0.4990647 ,  0.04170445,  0.17210223,
        0.93457367, -1.26883668, -1.18401448, -0.61495341,  1.26867243])

In [150]:
matrix2

array([[-0.35876674,  1.59887002, -0.51599763,  0.31247095],
       [ 0.8552852 , -1.20234461,  1.47137199,  0.26315125],
       [-0.49930132, -1.21331157,  0.32271951, -0.67149057],
       [-0.65977775,  0.14479942, -1.40319583,  1.33406283]])

In [151]:
matrix1.max(), matrix1.min()

(1.2883266216054674, -1.2688366759471643)

In [152]:
np.random?

# 집계함수와 정렬에서의 축

```
2차원에서 집계함수(sum, mean) 
axis=0/1
np.sum(넘파이배열명, axis=0/1)
np.mean(넘파이배열명, axis=0/1)
np.max(넘파이배열명, axis=0/1)
np.min(넘파이배열명, axis=0/1)

np.sort(넘파이배열명, axis=0/1)
```

In [156]:
# 정수 난수로 구성된 2*5 
m1 = np.random.randint(1,50, (2,5))
m1

array([[26, 29,  7,  2, 10],
       [41, 47,  2,  2, 43]])

In [157]:
# 세로방향으로 집계
np.sum(m1, axis=0)

array([67, 76,  9,  4, 53])

In [158]:
# 가로 방향으로 집계
np.sum(m1, axis=1)

array([ 74, 135])

In [162]:
# 1행의 합계는?
np.sum(m1[0, :])

74

In [161]:
np.sum(m1, axis=1)[0]

74

In [164]:
m1

array([[26, 29,  7,  2, 10],
       [41, 47,  2,  2, 43]])

In [163]:
np.max(m1, axis=1)

array([29, 47])

#### np.sort() 테스트 

In [167]:
# 정수 난수로 구성된 4*3 
m2 = np.random.randint(1,50, (4,3))
m2

array([[49, 32, 33],
       [24, 20, 49],
       [46, 37, 36],
       [34, 12, 18]])

In [168]:
# 세로 방향으로 값을 기준으로한 오름차순 정렬 
np.sort(m2, axis=0)

array([[24, 12, 18],
       [34, 20, 33],
       [46, 32, 36],
       [49, 37, 49]])

In [171]:
# 원본은 그대로 유지 
# 원본을 변경하려면?
m2 = np.sort(m2, axis=0)

In [172]:
m2

array([[24, 12, 18],
       [34, 20, 33],
       [46, 32, 36],
       [49, 37, 49]])

In [175]:
# 내림차순으로 다시 정렬 
m2 = m2[::-1, ::]
m2

array([[49, 37, 49],
       [46, 32, 36],
       [34, 20, 33],
       [24, 12, 18]])

In [173]:
np.sort?

# 인덱스 소팅 
```
np.argsort(배열명, axis=0/1)

넘파이배열[np.argsort 배열] => 오름차순한 결과 
```

In [176]:
np.argsort?

In [177]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [178]:
x[np.argsort(x)]

array([1, 2, 3])

In [179]:
np.sort(x)

array([1, 2, 3])

# 넘파이 배열의 추가와 삭제 

```
- 추가 
np.insert(배열명, 위치인덱스, 값, axis=0/1) 

2차원인 경우 axis를 설정하지 않는다면 1차원 배열로 변경된 후 값이 삽입된다. 
값은 리스트나 특정 숫자 


- 삭제 
np.delete(배열명, 위치인덱스, axis=0/1) 

```

In [180]:
np.insert?

In [181]:
mm1 = np.arange(1,11)
mm1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [184]:
# 첫번째 위치에 값 삽입 => 원본에 적용 
mm1 = np.insert(mm1, 0, 100)
mm1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [185]:
mm1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [193]:
# 끝에서 2번째에 데이타 삽입 
mm1 = np.insert(mm1, -1, 500)
mm1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [195]:
# 마지막 위치에 값 삽입 
mm1 = np.insert(mm1, len(mm1), 500)
mm1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10, 500])

In [196]:
mm2 = np.arange(1,10).reshape(3,3)
mm2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [197]:
# axis 값을 주지 않아서 1차원으로 변경 후 데이타 삽입 
np.insert(mm2, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [198]:
# 1행으로 [100, 100, 100] 생성해서 삽입 
np.insert(mm2, 0, 100, axis=0)

array([[100, 100, 100],
       [  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [199]:
# 1열로 [100, 100, 100] 생성해서 삽입 
np.insert(mm2, 0, 100, axis=1)

array([[100,   1,   2,   3],
       [100,   4,   5,   6],
       [100,   7,   8,   9]])

In [201]:
# 리스트로 삽입 - 첫번째 컬럼으로 삽입 
np.insert(mm2, 0, [100, 200, 300], axis=1)

array([[100,   1,   2,   3],
       [200,   4,   5,   6],
       [300,   7,   8,   9]])

In [204]:
# 리스트로 삽입 - 마지막 컬럼으로 삽입 
# 배열명.shape[1] 컬럼 길이 
# np.insert(배열명, 배열명.shape[1], 값이나 리스트, axis=1)
np.insert(mm2, mm2.shape[1], [100, 200, 300], axis=1)

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [205]:
# 첫번째 행으로 삽입 
np.insert(mm2, 0, [100, 200, 300], axis=0)

array([[100, 200, 300],
       [  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [206]:
# 마지막 행으로 삽입 
np.insert(mm2, mm2.shape[0], [100, 200, 300], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

In [207]:
np.delete?

In [209]:
mm2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [210]:
# 1행 삭제 
np.delete(mm2, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [211]:
# 1열 삭제 
np.delete(mm2, 0, axis=1)

array([[2, 3],
       [5, 6],
       [8, 9]])

# 배열간 합치기 

```
np.vstack((배열1, 배열2 .... )) : 세로로 합치기 
np.hstack((배열1, 배열2 .... )) : 가로로 합치기 
```

In [212]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print()
print(b)

[1 2 3]

[4 5 6]


In [215]:
# 2차원 배열 재구성
np.vstack((a,b)), np.vstack((a,b)).shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [216]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

#### np.concatenate() 메서드로 합치기 

In [219]:
c = np.array([[1,2,3]])
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [220]:
d = np.array([[4, 5, 6]])
d, d.ndim, d.shape

(array([[4, 5, 6]]), 2, (1, 3))

In [224]:
np.concatenate( (c, d), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [223]:
np.concatenate((c, d), axis=1)

array([[1, 2, 3, 4, 5, 6]])