In [1]:
# 쥬피터노트북 셀 스타일 조절 
from IPython.core.display import display, HTML
display(HTML("<style>.container { font-weight: bold !important; }</style>"))
display(HTML("<style>.container { width: 100% !important; }</style>"))

# 경고 메세지 숨기기 
import warnings
warnings.filterwarnings(action='ignore')

In [3]:
import numpy as np

# 불린 마스크 
조건절의 결과는 True, False 로 반환 <br>
True인 결과의 데이타프레임 반환 

```
 넘파이배열[조건절] 
 == , !=, <=, >=
 &, |, ~
 
```

In [4]:
matrix = np.arange(1,21)
matrix 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
# 넘파이 배열에 비교 연산자 적용 => True/False 값 반환 
matrix > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [7]:
# True 반환값의 갯수 
(matrix > 10).sum()

10

In [8]:
# 넘파이배열[조건절] => 조건절을 만족하는 실제값 반환 
matrix[matrix > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# 퀴즈 : 
# 1~100 사이의 숫자중에서 30개를 추출하여 랜덤하게 넘파이 배열을 생성하고 
# 30보다 크거나 70보다 작은 숫자를 출력하여라. 
# n>30 ? n<70

In [9]:
matrix2 = np.random.randint(1,100,30)
matrix2

array([65, 60, 66, 16, 48, 54, 64, 75, 31, 53, 96, 15, 89, 33, 71, 12, 63,
       19, 50, 10,  6, 84, 50, 99, 31, 21, 34, 66, 47, 74])

In [10]:
matrix2 > 30

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False,  True, False,
        True, False, False,  True,  True,  True,  True, False,  True,
        True,  True,  True])

In [11]:
matrix2[matrix2 > 30]

array([65, 60, 66, 48, 54, 64, 75, 31, 53, 96, 89, 33, 71, 63, 50, 84, 50,
       99, 31, 34, 66, 47, 74])

In [14]:
(matrix2 > 30).sum()

23

In [12]:
matrix2 < 70

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True, False,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True, False])

In [15]:
(matrix2 < 70).sum()

23

In [16]:
matrix2[matrix2 < 70]

array([65, 60, 66, 16, 48, 54, 64, 31, 53, 15, 33, 12, 63, 19, 50, 10,  6,
       50, 31, 21, 34, 66, 47])

In [21]:
# 30 < n < 70
(matrix2 > 30) & (matrix2 < 70)

array([ True,  True,  True, False,  True,  True,  True, False,  True,
        True, False, False, False,  True, False, False,  True, False,
        True, False, False, False,  True, False,  True, False,  True,
        True,  True, False])

In [18]:
((matrix2 > 30) & (matrix2 < 70)).sum()

16

In [22]:
matrix2[(matrix2 > 30) & (matrix2 < 70)]

array([65, 60, 66, 48, 54, 64, 31, 53, 33, 63, 50, 50, 31, 34, 66, 47])

In [25]:
matrix2[(matrix2 > 30) & (matrix2 < 70)]

array([65, 60, 66, 48, 54, 64, 31, 53, 33, 63, 50, 50, 31, 34, 66, 47])

In [26]:
#  (n <10 ) or (n > 90)
matrix2[(matrix2 < 10) | (matrix2 > 90)]

array([96,  6, 99])

In [27]:
# not ~  => 10 <= n <=90
matrix2[~((matrix2 < 10) | (matrix2 > 90))]

array([65, 60, 66, 16, 48, 54, 64, 75, 31, 53, 15, 89, 33, 71, 12, 63, 19,
       50, 10, 84, 50, 31, 21, 34, 66, 47, 74])

# 팬시 인덱싱 
```
 넘파이배열1[넘파이배열2]
 넘파이배열2 => 인덱스 역할 
```

In [28]:
matrix3 = np.random.randint(1,100,30)
matrix3

array([55, 92, 39, 92, 13, 73,  4, 51, 23,  8, 95, 52, 68, 84, 33, 92, 74,
       24, 14, 43, 69, 52,  5, 12, 23, 73, 76, 23, 56, 87])

In [37]:
# 필터링 인덱스 => 팬시 인덱싱 
# 정수 형태이어야 한다. 
matrix4 = np.array([0, 0, 0, 2, 3, 10, 20, -1])
matrix4

array([ 0,  0,  0,  2,  3, 10, 20, -1])

In [38]:
matrix3[matrix4]

array([55, 55, 55, 39, 92, 95, 69, 87])

In [39]:
matrix4 = np.random.randint(1,100,30).reshape(6,5)
matrix4

array([[82, 38, 37, 31, 19],
       [62, 51, 32, 89, 63],
       [66, 17, 52, 98, 60],
       [53, 23, 81, 26, 58],
       [80, 53, 91, 35,  2],
       [68, 80, 18, 66, 41]])

In [71]:
matrix5 = [ 0, 1, -1 ]

In [72]:
matrix4

array([[82, 38, 37, 31, 19],
       [62, 51, 32, 89, 63],
       [66, 17, 52, 98, 60],
       [53, 23, 81, 26, 58],
       [80, 53, 91, 35,  2],
       [68, 80, 18, 66, 41]])

In [73]:
# 1행, 2행, 마지막행 출력 
matrix4[ matrix5 ]

array([[82, 38, 37, 31, 19],
       [62, 51, 32, 89, 63],
       [68, 80, 18, 66, 41]])

In [86]:
matrix4 = np.arange(1,26).reshape(5,5)
matrix4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [94]:
# 배열[[행인덱스1, 행인덱스2 ...]]
matrix4[[0, 1, 2]]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [99]:
# 배열이름[ [i1, i2, i3 ... ], [j1, j2, j3 ... ]]
# [i1,j1], [i2,j2] ... 
# 대각선의 값만 출력
matrix4[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]

array([ 1,  7, 13, 19, 25])

In [105]:
# 별도 배열로 정의할려면 모두 튜플로 정의 
fancy = ((0, 1, 2, 3, 4), (0, 1, 2, 3, 4))
matrix4[fancy]

array([ 1,  7, 13, 19, 25])

In [97]:
matrix4[[0, 1, 2], 0:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [102]:
matrix4[[0, 1, 2], ::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15]])

In [101]:
matrix4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

##### 대각선 값 뽑기 

In [106]:
matrix4 = np.arange(1,26).reshape(5,5)
matrix4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [112]:
# 방법1
matrix4[0,0], matrix4[1,1], matrix4[2,2], matrix4[3,3], matrix4[4,4]

(1, 7, 13, 19, 25)

In [113]:
# 방법2
for i in range(len(matrix4)):
    print(matrix4[i, i], end='\t')

1	7	13	19	25	

In [114]:
# 방법3 - 팬시인덱싱 
matrix4[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]

array([ 1,  7, 13, 19, 25])

In [115]:
# 방법4
# 별도 배열로 정의할려면 모두 튜플이나 리스트로 정의 
# fancy = ((0, 1, 2, 3, 4), (0, 1, 2, 3, 4))
fancy = [[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]
matrix4[fancy]

array([ 1,  7, 13, 19, 25])

# np.where() 를 이용한 필터링 

```
np.where(조건식) => 조건식을 만족하는 인덱스 반환 

np.where(조건식, T, F) 
=> 조건식을 만족하면 T 값 그렇지않다면 F 값 

배열 [np.where(조건식)]
=> 조건식을 만족하는 실제 배열값이 반환 
```


In [116]:
np.where?

In [121]:
a = np.arange(20, 31)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [125]:
# 조건식을 만족하는 인덱스 반환
np.where(a < 25)

(array([0, 1, 2, 3, 4], dtype=int64),)

In [124]:
# 조건식을 만족하면 현재값 유지, 그렇지 않다면 10를 곱한다.
np.where(a < 25, a, 10*a)

array([ 20,  21,  22,  23,  24, 250, 260, 270, 280, 290, 300])

In [128]:
np.where(a < 25, 1, 0)

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0])

In [127]:
# 조건식을 만족하는 배열의 실제값 반환 
a[np.where(a < 25)]

array([20, 21, 22, 23, 24])