# Q1 넘파이 모듈을 np 별칭으로 임포트해라 

In [3]:
import numpy as np

# Q2 다음과 같은 리스트를 이용하여 

# 넘파이 배열을 만들고 

# 전체 갯수, 차원, 데이터형, 구조를 출력하여라 

```
['강아지', '원숭이', '꽃', '45', '100']

array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3')
차원 ? 1
전체 갯수 ? 5
데이터형 ? <U3
전체 구조  ? (5,)


```

# Q3 np.ones()를 이용하여 

# 2행 3열의 넘파이 배열을 생성하여라

```

array([[1., 1., 1.],
       [1., 1., 1.]])


```

# Q4. np.arange(), np.reshape()를 이용하여
# 다음과 같은 넘파이 배열을 생성하여라

```
array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])
       ```

# Q5. Q4의 넘파이 배열의 자료형을 

# float로 변경하고 데이터형을 출력하여라 

```

array([[51., 52., 53., 54., 55.],
       [56., 57., 58., 59., 60.],
       [61., 62., 63., 64., 65.],
       [66., 67., 68., 69., 70.],
       [71., 72., 73., 74., 75.],
       [76., 77., 78., 79., 80.]])
       
-------------------------------------  
  
dtype('float64')
       
       ```

# Q6. 다음과 같이 넘파이 배열을 생성한 후 
# 1차원 배열로 변경하고 슬라이싱하여라 

```
array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])
       
array([ 1,  4,  5,  6, 56, 23, 45, 67,  8,  4,  6, 10])


array([23, 45, 67,  8,  4,  6])
```       

# Q7. 다음과 같은 넘파이 배열을 생성한 후 
# 아이템을 교체하여라 

```
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

```

# Q8. 2자리의 숫자로 구성된 넘파이 배열(5행5열)을 만들어라.

# 숫자는 난수를 이용한다. 

```
[[63 85 71 67 15]
 [31 81 69 17 97]
 [25 41 33 23 39]
 [39 43 59 33 43]
 [23 51 65 91 23]]

```

# Q9. 1~100 사이의 정수중 7개의 숫자를 무작위로 추출한 후 가장 큰값과 가장 작은 값을 출력하여라. 

```
[91, 65, 14, 66, 65, 98, 34]

max = 98
min = 14
```

# Q10. 다음과 같은 3개의 넘파이 배열을 생성한 후 다음과 같이 합쳐라 


```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
 

[[11, 12, 13],
 [14, 15, 16],
 [17, 18, 19]]


[[21, 22, 23],
 [24, 25, 26],
 [27, 28, 29]]
 
 ----------
  Result1 
  
 [[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
  [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
  [ 7,  8,  9, 17, 18, 19, 27, 28, 29]] 
  
  
  ----------
  Result2
   
 [[ 1,  2,  3],
  [ 4,  5,  6],
  [ 7,  8,  9],
  [11, 12, 13],
  [14, 15, 16],
  [17, 18, 19],
  [21, 22, 23],
  [24, 25, 26],
  [27, 28, 29]] 
```


# Q11. 아래와 같이 넘파이 배열을 생성한 후 

# 50보다 큰 숫자만 필터링하여라. 

```
arr = np.random.choice(100, 40, replace=False)

Before => 

[40, 63,  8,  2, 35, 84, 72, 48, 78, 86, 87, 58,  0, 49, 14, 55, 11,
       73, 39, 26, 75, 27, 99, 46, 25, 22, 34, 83, 24, 47, 31, 57, 62, 19,
       36, 15, 17, 10, 98, 90]


After =>

[63, 84, 72, 78, 86, 87, 58, 55, 73, 75, 99, 83, 57, 62, 98, 90]


```

# Quiz 12

```

kor = np.array( [60,55,70,30,20,90])


1. 국어점수가 가장큰값을 구하여라
2. 국어점수가 80점이상인 값을 구하여라
3. 국어 점수가 50점이상 80점 이하인 값을 구하여라
4. 국어점수의 평균을 구하여라
5. 국어점수의 총합을 구하여라.
6. 국어점수가 40점이하인 데이터를 삭제하여라
7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하여라
8. 국어점수 top 5를 구하여라
9. 국어점수가 70점이상이면 '합격' , 아니면 '불합격으로' 아래와 같이 출력하시요

60 '불합격'
55 '불합격'
```

# Quiz 13

```
1) 아래 명령을 이용하여 ratings.dat 파일의 데이타를 넘파이 배열로 생성하여라

    np.loadtxt('data/ratings.dat', delimiter='::', dtype=np.int64)

    데이타형태는 다음과 같다. 
    ratings.dat => 무비렌즈의 영화평점데이타 
    (userId / movieId/rating/ timestamp)
     예) 1::1193::5:: 978300760

2) movieId 가 55인 데이타의 갯수는?

3) movieId 가 55인 데이타의 평균평점은? 

4) timestamp는 시계열데이타이다. timestamp 데이타를 이용하여 97년도 데이타만 추출한 후 
   총 데이타 갯수와 평균 평점을 구하여라
   
 ```

# Quiz 14

```
1) 'jeju2021.csv' 제주의 온도 데이타를 csv 파일로 저장한 후 
   np.loadtxt() 명령을 이용하여 필요한 컬럼과 데이터만 로딩하여라 
   
   '일시', '평균기온(℃)', '최고기온(℃)', '최저기온(℃)'
   
    data = np.loadtxt('data/jeju2021.csv', 
                        delimiter=',' , 
                        dtype=np.str ,
                       usecols=(2,3,5,8))
   
   

2) 1)의 넘파이 배열의 데이타 형태를 실수 형태로 변경하여라 
   데이타의 결측치나 이상값은 -99로 지정한다. 

[[20210101.0, 6.8, 18.2, -4.6],
 [20201201.0, 8.0, 16.3, -2.8],
 [20201101.0, 14.6, 26.7, 4.8],
 [20201001.0, 18.5, 25.8, 10.2],
 [20200901.0, 22.5, 32.5, 14.9],
 [20200801.0, 28.4, 36.3, 22.3],
 [20200701.0, 23.8, 34.3, 16.8],
 [20200601.0, 22.4, 30.9, 11.7],
 [20200501.0, 18.8, 29.5, 10.3],
 ...

3) 아래의 명령어를 이용하여 데이타값의 소숫점 처리를 3자리로 변경하여라 

np.set_printoptions(precision=3)
np.set_printoptions(formatter={'float_kind': lambda x: "{0:0.3f}".format(x)})

4) 제주도의 최고 기온은?

5) 2018년도 제주도 기온 데이타만 출력하여라. 

6) 최저 기온이 -5도 이하인 데이타만 출력하여라. 

7) 2018년도 기온 데이타에서 최고 기온이 28도 보다 높은 경우의 데이타만 출력하여라.
   
 ```

# Quiz 15

```
birthArr = np.loadtxt('data/births.txt',delimiter=',', dtype=np.int64)

1. 남아 ,여아 출생 평균을 구하여라
2. 남아출생이 가장많은 top5  를 구하여라(년도와 남아수)
3. 남아율(%) 을 구하고 각년도별  남아수가 차지하는비율을 데이터로  출력하여라 

년도    남아    여아    남아율
=================================
..
4. 2000년도 이후데이터 에 대해  출생량 을 구하고 
남아수가 1800000 이상이면 '많음'아니면 '적음' 이라고 출력하여라


	남아수 출생량
2000   1814601   '많음'
2001   1799049   '적음'


5.1800년대,1900년대,2000년대 각 남아,여야수 평균을 구하여라

```