In [1]:
# 쥬피터노트북 셀 스타일 조절 
from IPython.core.display import display, HTML
display(HTML("<style>.container { font-weight: bold !important; }</style>"))
display(HTML("<style>.container { width: 100% !important; }</style>"))

# 경고 메세지 숨기기 
import warnings
warnings.filterwarnings(action='ignore')

In [2]:
import numpy as np

In [5]:
ls data

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 2819-FF50

 C:\workspace211123\data 디렉터리

2021-11-23  오전 09:29    <DIR>          .
2021-11-23  오전 09:29    <DIR>          ..
2021-11-23  오전 12:12             3,088 births.txt
2021-11-23  오전 12:25            35,455 Jeju2021.csv
2016-07-17  오후 09:46           171,308 movies.dat
2018-04-24  오전 10:42        24,594,131 ratings.dat
2019-03-20  오전 10:54         1,185,149 seoul.csv
2021-01-31  오후 08:49            93,805 seoul2021.csv
               6개 파일          26,082,936 바이트
               2개 디렉터리  71,939,358,720 바이트 남음


# 외부 파일 연동 
```
배열명 = np.loadtxt('파일경로', delimeter='구분자', dtype=데이터형)
```

In [7]:
np.loadtxt?

In [9]:
# rating.dat 로딩 
rating = np.loadtxt('data/ratings.dat', delimiter='::', dtype=int)

In [11]:
rating.shape, rating.ndim, rating.dtype

((1000209, 4), 2, dtype('int32'))

In [12]:
# 3개만 출력 
rating[:3, :]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968]])

In [18]:
# 3열이 평점 
# 3열의 평점의 평균은?

In [19]:
rating[:, 2]

array([5, 3, 3, ..., 5, 4, 4])

In [20]:
rating[:, 2].mean()

3.581564453029317

In [23]:
# 중복값 없이 배열값 표시 
np.unique?

In [25]:
# 사용자 수?

In [26]:
rating[:, 0] # 1열 

array([   1,    1,    1, ..., 6040, 6040, 6040])

In [27]:
np.unique(rating[:, 0])

array([   1,    2,    3, ..., 6038, 6039, 6040])

In [28]:
np.unique(rating[:, 0]).size

6040

In [29]:
len(np.unique(rating[:, 0]))

6040

In [ ]:
# 퀴즈 : 
# 1) userId가 2인 배열값만 출력?
# 2) userId가 2인 사람의 평점의 평균은?

In [31]:
rating[:,0] == 2

array([False, False, False, ..., False, False, False])

In [35]:
user2 = rating[rating[:,0] == 2]
user2[:5, :]

array([[        2,      1357,         5, 978298709],
       [        2,      3068,         4, 978299000],
       [        2,      1537,         4, 978299620],
       [        2,       647,         3, 978299351],
       [        2,      2194,         4, 978299297]])

In [37]:
user2[:, 2].mean()

3.7131782945736433

In [38]:
f'user id 가 2인 사람의 평점의 평균은? {user2[:, 2].mean():.2f}'

'user id 가 2인 사람의 평점의 평균은? 3.71'

# np.savetxt()

- 파일 저장 
```
np.savetxt('파일경로', 배열이름, fmt='포맷형식', delimiter='구분자') 
```

In [41]:
# 100개의 데이타만 output 폴더안에 csv 파일 형태로 저장하기 
rating100 = rating[:100, :]
len(rating100)

100

In [44]:
import os 

try:
    # 현재 폴더를 기준으로 폴더 생성 
    os.mkdir('output')
except:
    print('폴더가 이미 생성되었어요 !!! ')

폴더가 이미 생성되었어요 !!! 


In [48]:
# 파일과 폴더 목록보기 

In [49]:
# ls

In [50]:
np.savetxt?

In [56]:
# np.savetxt('output/rating100.csv', rating100, delimiter=',', fmt='%.2f')
np.savetxt('output/rating100.csv', rating100, delimiter=',', fmt='%d')

In [53]:
ls output

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 2819-FF50

 C:\workspace211123\output 디렉터리

2021-11-24  오후 02:34    <DIR>          .
2021-11-24  오후 02:34    <DIR>          ..
2021-11-24  오후 02:34            10,100 rating100.csv
               1개 파일              10,100 바이트
               2개 디렉터리  70,292,295,680 바이트 남음
