In [9]:
# 쥬피터노트북 셀 스타일 조절 
from IPython.core.display import display, HTML
display(HTML("<style>.container { font-weight: bold !important; }</style>"))
display(HTML("<style>.container { width: 100% !important; }</style>"))

# 경고 메세지 숨기기 
import warnings
warnings.filterwarnings(action='ignore')

# Q1 넘파이 모듈을 np 별칭으로 임포트해라 

In [10]:
import numpy as np

# Q2 다음과 같은 리스트를 이용하여 

# 넘파이 배열을 만들고 

# 전체 갯수, 차원, 데이터형, 구조를 출력하여라 

```
['강아지', '원숭이', '꽃', '45', '100']

array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3')
차원 ? 1
전체 갯수 ? 5
데이터형 ? <U3
전체 구조  ? (5,)


```

In [4]:
myList = ['강아지','원숭이','꽃',45,100]
myListMatrix =  np.array(myList)
print(myListMatrix)
print('차원 ? ', myListMatrix.ndim)
print('데이터형 ?', myListMatrix.dtype)
print('전체 구조  ? ', myListMatrix.shape)

['강아지' '원숭이' '꽃' '45' '100']
차원 ?  1
데이터형 ? <U11
전체 구조  ?  (5,)


# Q3 np.ones()를 이용하여 

# 2행 3열의 넘파이 배열을 생성하여라

```

array([[1., 1., 1.],
       [1., 1., 1.]])


```

In [5]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.ones(6).reshape(2,3).astype(int)

array([[1, 1, 1],
       [1, 1, 1]])

# Q4. np.arange(), np.reshape()를 이용하여
# 다음과 같은 넘파이 배열을 생성하여라

```
array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])
       ```

In [11]:
np.arange(51,81).reshape(6,5)

array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])

In [13]:
arr = np.arange(51,81).reshape(-1,5)
arr

array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])

# Q5. Q4의 넘파이 배열의 자료형을 

# float로 변경하고 데이터형을 출력하여라 

```

array([[51., 52., 53., 54., 55.],
       [56., 57., 58., 59., 60.],
       [61., 62., 63., 64., 65.],
       [66., 67., 68., 69., 70.],
       [71., 72., 73., 74., 75.],
       [76., 77., 78., 79., 80.]])
       
-------------------------------------  
  
dtype('float64')
       
       ```

In [14]:
arr = np.arange(51,81).reshape(-1,5)
arr.dtype

dtype('int32')

In [17]:
arr = arr.astype(float)

In [19]:
arr.dtype

dtype('float64')

# Q6. 다음과 같이 넘파이 배열을 생성한 후 
# 1차원 배열로 변경하고 슬라이싱하여라 

```
array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])
       
array([ 1,  4,  5,  6, 56, 23, 45, 67,  8,  4,  6, 10])


array([23, 45, 67,  8,  4,  6])
```       

In [20]:
arr2d = np.array([[1,4,5,6],[56,23,45,67],[8,4,6,10]])
arr2d

array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])

In [28]:
arr2d= arr2d.flatten()
arr2d

array([ 1,  4,  5,  6, 56, 23, 45, 67,  8,  4,  6, 10])

In [27]:
arr2d[5:-1], arr2d[5:11]

(array([23, 45, 67,  8,  4,  6]), array([23, 45, 67,  8,  4,  6]))

# Q7. 다음과 같은 넘파이 배열을 생성한 후 
# 아이템을 교체하여라 

```
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

```

In [29]:
matrix = np.arange(1,11)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
matrix[0] = 10
matrix

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
matrix[7:] = 0
matrix

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

# Q8. 2자리의 숫자로 구성된 넘파이 배열(5행5열)을 만들어라.

# 숫자는 난수를 이용한다. 

```
[[63 85 71 67 15]
 [31 81 69 17 97]
 [25 41 33 23 39]
 [39 43 59 33 43]
 [23 51 65 91 23]]

```

In [32]:
np.random.randint(10,99,25).reshape(5,5)

array([[71, 51, 87, 69, 54],
       [11, 90, 77, 75, 74],
       [39, 73, 46, 87, 45],
       [28, 93, 75, 83, 81],
       [77, 34, 61, 71, 97]])

In [33]:
np.random.randint(10,99,25).reshape(-1,5)

array([[90, 28, 31, 63, 95],
       [90, 37, 44, 90, 91],
       [38, 12, 86, 69, 75],
       [72, 32, 76, 11, 17],
       [55, 85, 51, 15, 57]])

In [34]:
np.random.randint(10,99,(5,5))

array([[76, 10, 23, 82, 88],
       [37, 15, 67, 79, 31],
       [26, 84, 98, 29, 68],
       [40, 29, 74, 52, 97],
       [10, 85, 21, 91, 79]])

# Q9. 1~100 사이의 정수중 7개의 숫자를 무작위로 추출한 후 가장 큰값과 가장 작은 값을 출력하여라. 

```
[91, 65, 14, 66, 65, 98, 34]

max = 98
min = 14
```

In [35]:
arr = np.random.randint(1,100,7)
arr

array([40, 79, 15, 19, 93,  7, 86])

In [36]:
np.max(arr), np.min(arr)

(93, 7)

In [37]:
arr.max(), arr.min()

(93, 7)

# Q10. 다음과 같은 3개의 넘파이 배열을 생성한 후 다음과 같이 합쳐라 


```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
 

[[11, 12, 13],
 [14, 15, 16],
 [17, 18, 19]]


[[21, 22, 23],
 [24, 25, 26],
 [27, 28, 29]]
 
 ----------
  Result1 
  
 [[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
  [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
  [ 7,  8,  9, 17, 18, 19, 27, 28, 29]] 
  
  
  ----------
  Result2
   
 [[ 1,  2,  3],
  [ 4,  5,  6],
  [ 7,  8,  9],
  [11, 12, 13],
  [14, 15, 16],
  [17, 18, 19],
  [21, 22, 23],
  [24, 25, 26],
  [27, 28, 29]] 
```


In [38]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
arr3 = np.arange(21,30).reshape(3,3)

In [39]:
print(arr1)
print()
print(arr2)
print()
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]

[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [43]:
np.hstack((arr1, arr2, arr3))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
       [ 7,  8,  9, 17, 18, 19, 27, 28, 29]])

In [46]:
np.concatenate( (arr1, arr2, arr3), axis=1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
       [ 7,  8,  9, 17, 18, 19, 27, 28, 29]])

In [44]:
np.vstack((arr1, arr2, arr3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [45]:
np.concatenate( (arr1, arr2, arr3), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

# Q11. 아래와 같이 넘파이 배열을 생성한 후 

# 50보다 큰 숫자만 필터링하여라. 

```
arr = np.random.choice(100, 40, replace=False)

Before => 

[40, 63,  8,  2, 35, 84, 72, 48, 78, 86, 87, 58,  0, 49, 14, 55, 11,
       73, 39, 26, 75, 27, 99, 46, 25, 22, 34, 83, 24, 47, 31, 57, 62, 19,
       36, 15, 17, 10, 98, 90]


After =>

[63, 84, 72, 78, 86, 87, 58, 55, 73, 75, 99, 83, 57, 62, 98, 90]


```

In [53]:
np.random.choice?

In [59]:
# 중복값없이 뽑기 
arr = np.random.choice(100, 40, replace=False)
arr

array([38, 83, 50, 30, 73, 95, 74, 52, 18, 57, 58, 91, 13, 86,  5,  6, 72,
       85, 28, 23, 33, 20, 69, 78, 26, 82, 98,  9, 36, 90, 87, 61, 43, 49,
       64, 39, 75,  3, 59, 92])

In [58]:
# np.random.randint(0,10, 8)

array([1, 6, 4, 0, 6, 7, 9, 9])

In [60]:
arr >= 50

array([False,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True, False,  True, False, False,  True,  True,
       False, False, False, False,  True,  True, False,  True,  True,
       False, False,  True,  True,  True, False, False,  True, False,
        True, False,  True,  True])

In [61]:
arr[arr >= 50]

array([83, 50, 73, 95, 74, 52, 57, 58, 91, 86, 72, 85, 69, 78, 82, 98, 90,
       87, 61, 64, 75, 59, 92])

In [67]:
arr[np.where(arr >= 50)]

array([83, 50, 73, 95, 74, 52, 57, 58, 91, 86, 72, 85, 69, 78, 82, 98, 90,
       87, 61, 64, 75, 59, 92])

In [65]:
np.where(arr >= 50, arr, 0)

array([ 0, 83, 50,  0, 73, 95, 74, 52,  0, 57, 58, 91,  0, 86,  0,  0, 72,
       85,  0,  0,  0,  0, 69, 78,  0, 82, 98,  0,  0, 90, 87, 61,  0,  0,
       64,  0, 75,  0, 59, 92])

# Quiz 12

```

kor = np.array( [60,55,70,30,20,90])


1. 국어점수가 가장큰값을 구하여라
2. 국어점수가 80점이상인 값을 구하여라
3. 국어 점수가 50점이상 80점 이하인 값을 구하여라
4. 국어점수의 평균을 구하여라
5. 국어점수의 총합을 구하여라.
6. 국어점수가 40점이하인 데이터를 삭제하여라
7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하여라
8. 국어점수 top 3를 구하여라
9. 국어점수가 70점이상이면 '합격' , 아니면 '불합격으로' 아래와 같이 출력하시요

60 '불합격'
55 '불합격'
```

In [68]:
kor = np.array( [60,55,70,30,20,90])

In [69]:
# 1)
kor.max()

90

In [71]:
# 2)
kor[kor>=80]

array([90])

In [73]:
# 3) 50점이상 80점 이하
kor[(kor>=50) & (kor<=80)]

array([60, 55, 70])

In [76]:
# 4) 평균 
round(kor.mean(),3)

54.167

In [77]:
# 5) 총합 
kor.sum()

325

In [ ]:
# 6. 국어점수가 40점이하인 데이터를 삭제하시요

In [78]:
# 40점이하인 데이터의 인덱스 반환 
np.where( kor<=40)

(array([3, 4], dtype=int64),)

In [79]:
np.delete(kor, np.where( kor<=40) )

array([60, 55, 70, 90])

In [82]:
kor2 = np.delete(kor, np.where( kor<=40) )
kor2

array([60, 55, 70, 90])

In [85]:
# 7. 국어점수가 50점이상인 데이터에 가산점 10%를  부여하시요
kor

array([60, 55, 70, 30, 20, 90])

In [86]:
kor[ kor>=50 ]

array([60, 55, 70, 90])

In [88]:
# 자동 float 형으로 변경
kor[ kor>=50 ]*1.1

array([66. , 60.5, 77. , 99. ])

In [89]:
np.where(kor>=50, kor*1.1, kor)

array([66. , 60.5, 77. , 30. , 20. , 99. ])

In [90]:
# 8. 국어점수 top 3를 구하시요

In [92]:
np.sort(kor)[::-1]

array([90, 70, 60, 55, 30, 20])

In [93]:
np.sort(kor)[::-1][:3]

array([90, 70, 60])

In [ ]:
tmp_14 = kor[kor.argsort()[-3:][::-1]]
print(tmp_14)

In [96]:
kor.argsort(), kor[kor.argsort()[-3:]]

(array([4, 3, 1, 0, 2, 5], dtype=int64), array([60, 70, 90]))

In [112]:
kor = np.array( [60,55,70,30,20,90])

In [113]:
kor.argsort(), kor[kor.argsort()[-3:][::-1]]

(array([4, 3, 1, 0, 2, 5], dtype=int64), array([90, 70, 60]))

In [98]:
np.sort(kor)[-1:-4:-1]

array([90, 70, 60])

In [99]:
# 9. 국어점수가 70점이상이면 '합격' , 아니면 '불합격으로'
# 아래와 같이 출력하시요
# 60 '불합격'
# 55 '불합격'

In [100]:
for n in kor:
    if n>=70: 
        print(n, '합격')
    else:
        print(n, '불합격')

60 불합격
55 불합격
70 합격
30 불합격
20 불합격
90 합격


In [101]:
np.where(kor>=70,"합격","불합격")

array(['불합격', '불합격', '합격', '불합격', '불합격', '합격'], dtype='<U3')

In [105]:
result = np.where(kor>=70,"합격","불합격")
result

array(['불합격', '불합격', '합격', '불합격', '불합격', '합격'], dtype='<U3')

In [107]:
kor

array([60, 55, 70, 30, 20, 90])

In [108]:
for i in range(len(result)):
    print(kor[i], result[i])

60 불합격
55 불합격
70 합격
30 불합격
20 불합격
90 합격


# Quiz 13

```
1) 아래 명령을 이용하여 ratings.dat 파일의 데이타를 넘파이 배열로 생성하여라

    np.loadtxt('data/ratings.dat', delimiter='::', dtype=np.int64)

    데이타형태는 다음과 같다. 
    ratings.dat => 무비렌즈의 영화평점데이타 
    (userId / movieId/rating/ timestamp)
     예) 1::1193::5:: 978300760

2) movieId 가 55인 데이타의 갯수는?

3) movieId 가 55인 데이타의 평균평점은? 

4) timestamp는 시계열데이타이다. timestamp 데이타를 이용하여 97년도 데이타만 추출한 후 
   총 데이타 갯수와 평균 평점을 구하여라
   
 ```

In [ ]:
# 1) 
data = np.loadtxt('data/jeju2021.csv', delimiter=',' , dtype=np.str ,
                   usecols=(2,3,5,8))
data[11:, :]

# Quiz 14

```
1) 'jeju2021.csv' 제주의 온도 데이타를 csv 파일로 저장한 후 
   np.loadtxt() 명령을 이용하여 필요한 컬럼과 데이터만 로딩하여라 
   
   '일시', '평균기온(℃)', '최고기온(℃)', '최저기온(℃)'
   
    data = np.loadtxt('data/jeju2021.csv', 
                        delimiter=',' , 
                        dtype=np.str ,
                       usecols=(2,3,5,8))
   
   

2) 1)의 넘파이 배열의 데이타 형태를 실수 형태로 변경하여라 
   데이타의 결측치나 이상값은 -99로 지정한다. 

[[20210101.0, 6.8, 18.2, -4.6],
 [20201201.0, 8.0, 16.3, -2.8],
 [20201101.0, 14.6, 26.7, 4.8],
 [20201001.0, 18.5, 25.8, 10.2],
 [20200901.0, 22.5, 32.5, 14.9],
 [20200801.0, 28.4, 36.3, 22.3],
 [20200701.0, 23.8, 34.3, 16.8],
 [20200601.0, 22.4, 30.9, 11.7],
 [20200501.0, 18.8, 29.5, 10.3],
 ...

3) 아래의 명령어를 이용하여 데이타값의 소숫점 처리를 3자리로 변경하여라 
( 지수형태의 숫자 => 소숫점 형태 )
np.set_printoptions(precision=3)
np.set_printoptions(formatter={'float_kind': lambda x: "{0:0.3f}".format(x)})

4) 제주도의 최고 기온은?

5) 2018년도 제주도 기온 데이타만 출력하여라. 

6) 최저 기온이 -5도 이하인 데이타만 출력하여라. 

7) 2018년도 기온 데이타에서 최고 기온이 28도 보다 높은 경우의 데이타만 출력하여라.
   
 ```

In [154]:
np.set_printoptions?

In [16]:
# 전체 모두 텍스트 형식으로 넘파이 배열 생성 
data = np.loadtxt('data/jeju2021.csv', 
                        delimiter=',' , 
                        dtype=np.str)
data

array([['10', '제주', '2021-01-01', ..., '', '', ''],
       ['10', '제주', '2020-12-01', ..., '', '', ''],
       ['10', '제주', '2020-11-01', ..., '', '', ''],
       ...,
       ['\t', '', '', ..., '', '', ''],
       ['\t', '', '', ..., '', '', ''],
       ['\t', '', '', ..., '', '', '']], dtype='<U10')

In [17]:
data[1,:]

array(['10', '제주', '2020-12-01', '8', '11.3', '16.3', '성산', '5.1', '-2.8',
       '성산', '', '', ''], dtype='<U10')

In [18]:
data.shape

(583, 13)

In [19]:
# '일시', '평균기온(℃)', '최고기온(℃)', '최저기온(℃)'
# 컬럼만 넘파이 배열로 생성 
data = np.loadtxt('data/jeju2021.csv', 
                        delimiter=',' , 
                        dtype=np.str ,
                       usecols=(2,3,5,8))
data

array([['2021-01-01', '6.8', '18.2', '-4.6'],
       ['2020-12-01', '8', '16.3', '-2.8'],
       ['2020-11-01', '14.6', '26.7', '4.8'],
       ...,
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U10')

In [20]:
data.shape

(583, 4)

In [ ]:
# 2) 1)의 넘파이 배열의 데이타 형태를 실수 형태로 변경하여라 
#   데이타의 결측치나 이상값은 -99로 지정한다. 

In [22]:
# ValueError 발생 
# data.astype(float)

In [23]:
# 데이타가 없는 갯수는?
len(data[data[:, 0] == ''])

6

In [26]:
# 값이 없는 데이타 출력 
# data[:, 0] == ''
data[data[:, 0] == '']

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U10')

In [27]:
data[0]

array(['2021-01-01', '6.8', '18.2', '-4.6'], dtype='<U10')

In [30]:
float('2021-01-01'.replace('-',''))

20210101.0

In [31]:
# 빈 리스트 생성 
result = []
for row in data:
    temp = []
    try:
        if row[0]:
            # '2021-01-01' => 20210101
            date = float(row[0].replace('-',''))
        else:
            date=-99
        temp.append(date) # [20210101.0, 6.8, 18.2, -4.6]
        # 각행의 2,3,4 값 처리 
        # 숫자.숫자 형태라면 실수형태로 변경해서 삽입 
        # 그외에는 -99 입력 
        for item in row[1:]:            
            try:
                temp.append(float(item)) 
            except:
                temp.append(-99)

    except:
        pass
    
    else:
        result.append(temp)  

In [32]:
len(data), len(result)

(583, 583)

In [33]:
result[-7:]

[[19730101.0, 7.5, 19.6, -1.6],
 [-99, -99, -99, -99],
 [-99, -99, -99, -99],
 [-99, -99, -99, -99],
 [-99, -99, -99, -99],
 [-99, -99, -99, -99],
 [-99, -99, -99, -99]]

In [34]:
# 넘파이 배열화 
arr_jeju = np.array(result)
arr_jeju

array([[ 2.0210101e+07,  6.8000000e+00,  1.8200000e+01, -4.6000000e+00],
       [ 2.0201201e+07,  8.0000000e+00,  1.6300000e+01, -2.8000000e+00],
       [ 2.0201101e+07,  1.4600000e+01,  2.6700000e+01,  4.8000000e+00],
       ...,
       [-9.9000000e+01, -9.9000000e+01, -9.9000000e+01, -9.9000000e+01],
       [-9.9000000e+01, -9.9000000e+01, -9.9000000e+01, -9.9000000e+01],
       [-9.9000000e+01, -9.9000000e+01, -9.9000000e+01, -9.9000000e+01]])

In [36]:
# Q2
# 지수 => 소숫점화 해서 표시 
np.set_printoptions(precision=3)
np.set_printoptions(formatter={'float_kind': lambda x: "{0:0.3f}".format(x)})

In [37]:
arr_jeju

array([[20210101.000, 6.800, 18.200, -4.600],
       [20201201.000, 8.000, 16.300, -2.800],
       [20201101.000, 14.600, 26.700, 4.800],
       ...,
       [-99.000, -99.000, -99.000, -99.000],
       [-99.000, -99.000, -99.000, -99.000],
       [-99.000, -99.000, -99.000, -99.000]])

In [ ]:
# 4) 제주도의 최고 기온은? 그리고 날짜는?
#  '일시', '평균기온(℃)', '최고기온(℃)', '최저기온(℃)'

In [38]:
# arr_jeju2 : 최고기온 에서 -99 가 없는 넘파이 배열 생성 
arr_jeju2 = arr_jeju[arr_jeju[:,2]!=-99]

In [39]:
arr_jeju.shape, arr_jeju2.shape

((583, 4), (577, 4))

In [40]:
# 최고기온의 max
arr_jeju_max = np.max(arr_jeju2[:,2])
arr_jeju_max

37.4

In [42]:
# 최고기온 max의 날짜는?
arr_jeju2[arr_jeju2[:, 2]==arr_jeju_max]

array([[19980801.000, 27.900, 37.400, 19.100]])

In [43]:
arr_jeju2[arr_jeju2[:, 2]==arr_jeju_max][0,0]

19980801.0

In [44]:
arr_jeju_max_date = str(int(arr_jeju[arr_jeju[:, 2]==arr_jeju_max][0, 0]))
arr_jeju_max_date

'19980801'

In [47]:
arr_jeju_max_date2 = (arr_jeju_max_date[:4], arr_jeju_max_date[4:6], arr_jeju_max_date[-2:])

In [48]:
f'날짜 : {arr_jeju_max_date2[0]}년 {arr_jeju_max_date2[1]}월 {arr_jeju_max_date2[2]}일  기온 : {arr_jeju_max}'

'날짜 : 1998년 08월 01일  기온 : 37.4'

In [50]:
# 5) 2018년도 제주도 기온 데이타만 출력하여라

arr_jeju2018 = arr_jeju[(arr_jeju[:, 0] >= 20180000) & (arr_jeju[:, 0] < 20190000)]
arr_jeju2018

array([[20181201.000, 9.300, 22.900, -1.000],
       [20181101.000, 14.200, 21.800, 3.800],
       [20181001.000, 17.900, 27.000, 7.900],
       [20180901.000, 23.700, 31.200, 21.300],
       [20180801.000, 28.300, 35.500, 22.300],
       [20180701.000, 27.000, 35.000, 19.400],
       [20180601.000, 22.200, 32.300, 13.100],
       [20180501.000, 18.900, 31.100, 6.700],
       [20180401.000, 15.900, 26.100, 0.500],
       [20180301.000, 11.600, 23.200, 1.700],
       [20180201.000, 5.900, 17.500, -3.800],
       [20180101.000, 5.400, 16.200, -3.700]])

In [53]:
# 6) 최저 기온이 -5도 이하인 데이타만 출력하여라.
arr_jeju2[(arr_jeju2[:, 3] <= -5) & (arr_jeju2[:, 3] > -99 )]

array([[20160101.000, 6.200, 17.500, -6.900],
       [20010201.000, 7.600, 22.600, -5.100],
       [19900101.000, 5.600, 18.600, -7.000],
       [19810201.000, 5.800, 16.200, -5.700],
       [19810101.000, 4.100, 15.000, -5.000],
       [19770201.000, 4.500, 17.500, -6.400]])

In [54]:
# 7) 2018년도 기온 데이타에서 최고 기온이 28도 보다 높은 경우의 데이타만 출력하여라.

In [55]:
arr_jeju2018[arr_jeju2018[:, 2] >= 28 ]

array([[20180901.000, 23.700, 31.200, 21.300],
       [20180801.000, 28.300, 35.500, 22.300],
       [20180701.000, 27.000, 35.000, 19.400],
       [20180601.000, 22.200, 32.300, 13.100],
       [20180501.000, 18.900, 31.100, 6.700]])

# Quiz 15

```
birthArr = np.loadtxt('data/births.txt',delimiter=',', dtype=np.int64)
데이타 구성은?
년도  남아  여아 


1. 남아 ,여아 출생 평균을 구하여라
2. 남아출생이 가장많은 top5  를 구하여라(년도와 남아수)
3. 남아율(%) 을 구하고 각년도별  남아수가 차지하는비율을 데이터로  출력하여라 

년도    남아    여아    남아율
=================================
..
4. 2000년도 이후데이터 에 대해  출생량 을 구하고 
남아수가 1800000 이상이면 '많음'아니면 '적음' 이라고 출력하여라


	남아수 출생량
2000   1814601   '많음'
2001   1799049   '적음'


5.1800년대,1900년대,2000년대 각 남아,여야수 평균을 구하여라

```

In [141]:
birthArr = np.loadtxt('data/births.txt',delimiter=',',
                     dtype=int)
birthArr.shape

(132, 3)

In [118]:
# 1. 남아 ,여아 출생 평균을 구하시요
result = birthArr.mean(axis=0)
print( '남아평균:', round( result[1],2), round(birthArr[:, 1].mean(),2) )
print( '여아평균:', round( result[2],2), round(birthArr[:, 2].mean(),2) )

남아평균: 1225776.07 1225776.07
여아평균: 1245399.21 1245399.21


In [ ]:
# 2. 남아출생이 가장많은 top5 구하시요(년도와 남아수)

In [124]:
top5 = np.sort(birthArr[:, 1])[::-1][:5]
print(top5)
idx = np.argsort(birthArr[:, 1])[::-1][:5]
print(idx)
birthArr[ idx ][:, :2]

[2044160 2023044 2022093 2017316 2010884]
[77 79 80 81 78]


array([[   1957, 2044160],
       [   1959, 2023044],
       [   1960, 2022093],
       [   1961, 2017316],
       [   1958, 2010884]])

In [123]:
# 2번째 방법
idx = np.argsort( birthArr[:, 1]  )[-1:-6:-1]
birthArr[ idx ][:, 0:-1]

array([[   1957, 2044160],
       [   1959, 2023044],
       [   1960, 2022093],
       [   1961, 2017316],
       [   1958, 2010884]])

In [125]:
# 3. 남아율(%) 을 구하고 각년도별  남아수가 차지하는비율을 데이터로 보여주시요.
# 년도    남아    여아    남아율
# =================================
# ..

In [126]:
print( '년도','남아','여아','남아율')
print('=================================')
for y, m, f in birthArr:
    print( y,m,f, round(m/(m+f)*100,2) )

년도 남아 여아 남아율
1880 90993 110491 45.16
1881 91954 100745 47.72
1882 107850 113688 48.68
1883 112321 104629 51.77
1884 129022 114445 52.99
1885 133055 107800 55.24
1886 144535 110784 56.61
1887 145982 101414 59.01
1888 178627 120853 59.65
1889 178366 110584 61.73
1890 190377 111025 63.16
1891 185482 101196 64.7
1892 212346 122037 63.5
1893 212906 112317 65.46
1894 222922 115772 65.82
1895 233630 117398 66.56
1896 237920 119570 66.55
1897 234202 112758 67.5
1898 258770 122693 67.84
1899 233023 106212 68.69
1900 299828 150499 66.58
1901 239348 106471 69.21
1902 264077 122659 68.28
1903 261973 119234 68.72
1904 275371 128125 68.25
1905 291629 132319 68.79
1906 295303 133159 68.92
1907 318566 146833 68.45
1908 334313 154344 68.41
1909 347228 163999 67.92
1910 396501 194218 67.12
1911 418299 225968 64.93
1912 558103 429945 56.49
1913 624518 512557 54.92
1914 761548 654762 53.77
1915 983874 848603 53.69
1916 1044323 890099 53.99
1917 1081280 925511 53.88
1918 1157647 1013537 53.32
1919 1130145 

In [127]:
# 4. 2000년도 이후데이터 에 대해
# 출생량 을 구하고
# 남아수가 1800000 이상이면 '많음'아니면 '적음'
# 이라고 보여 주시요
# 	남아수 출생량
# 2000   1814601   '많음'
# 2001   1799049   '적음'

In [133]:
arr2000 = birthArr[ birthArr[:,0]>=2000 ]
print('남아수 출생량')
for y,m,f in arr2000:
    print( y, m, end=' ' )
    if m>=1800000:
        print('많음')
    else:
        print('적음')

남아수 출생량
2000 1814601 많음
2001 1799049 적음
2002 1795206 적음
2003 1825359 많음
2004 1834145 많음
2005 1845379 많음
2006 1898463 많음
2007 1919408 많음
2008 1887234 많음
2009 1832925 많음
2010 1772738 적음
2011 1753500 적음


In [131]:
# 5.1800년대,1900년대,2000년대 각 남아,여야수 평균을 구하시요

In [134]:
arr1800 = birthArr[ (birthArr[:,0]>=1800) & (birthArr[:,0]<=1899)]
a1800Mean = arr1800.mean(axis=0)
print( '1800년대 남아평균', a1800Mean[1])
print( '1800년대 여아평균', a1800Mean[2])

1800년대 남아평균 176714.15
1800년대 여아평균 111820.55


In [135]:
arr1900 = birthArr[ (birthArr[:,0]>=1900) & (birthArr[:,0]<=1999)]
a1900Mean = arr1900.mean(axis=0)
print( '1900년대 남아평균', a1900Mean[1])
print( '1900년대 여아평균', a1900Mean[2])

1900년대 남아평균 1362901.51
1900년대 여아평균 1384145.55


In [136]:
arr2000 = birthArr[ birthArr[:,0]>=2000]
a2000Mean = arr2000.mean(axis=0)
print( '2000 년도 남아평균', a2000Mean[1])
print( '2000 년도 여아평균', a2000Mean[2])

2000 년도 남아평균 1831500.5833333333
2000 년도 여아평균 1978477.5
